### ISSUE TITLE
Choosing languages to see posts in

### ISSUE THREAD

**Issue by FitikWasTaken** [jwr1/interstellar#15]
### Describe the feature you'd like to request

Add the ability in setting to choose in languages of posts (threads/microblogs) you see on Feed. I think it would be especially helpful to all non-English speaking users, but would be helpful to English speakers who wish to not see non English content as well

### Additional context

Additionally it would be useful if there was ability to choose new post language (when you create them) like on web frontend

**Comment by jwr1** [comment]
The next release includes these features. Hopefully, I added everything you were thinking of.

![image](https://github.com/jwr1/interstellar/assets/47087725/a3d981a9-11e2-43d0-92f4-a41f69c4224a)
