### ISSUE TITLE
Log in to some Lemmy servers fails

### ISSUE THREAD

**Issue by godkarmachine** [jwr1/interstellar#27]
### Describe the bug

An error message appears when attempting to log in to some Lemmy servers. Issue was noted on lemmy.blahaj.zone, but may also occur on other servers. Midwest.social was noted as working as expected. 

### Steps to Reproduce

1. Go to add account
2. Enter an affected Lemmy instance (such as lemmy.blahaj.zone) under instance host and tap Continue
3. Enter a user name and password
4. Error message will appear as in screenshot below

![Screenshot_20240302-221834_1](https://github.com/jwr1/interstellar/assets/1330252/b8ca4a03-6ea6-4815-a325-96b190f7e7a9)

### Version

0.4.0

### What platform(s) are you seeing the problem on?

Android

**Comment by olorin99** [comment]
Pretty sure this is to do with the Lemmy version the server is using.

Don't work
lemmy.blahaj.zone - v0.18.4
lemmy.world - v0.18.5

Work
midwest.social - v0.19.3
lemm.ee - v0.19.3
programming.dev - v0.19.3

There seems to have been a change in the /api/v3/site request and we're using the updated version which has a different structure to the previous API.

Not sure if we should add a fix in app or should just wait for the servers to update to the latest version of Lemmy.

**Comment by jwr1** [comment]
> Pretty sure this is to do with the Lemmy version the server is using.

That seems to be the case. If we wanted to add v0.18.x support, we'd also have to fix the post pagination since the page_cursor wasn't added till v0.19.0, and who knows what else would need to be fixed. I'd say we should just wait till the servers upgrade.

**Comment by jwr1** [comment]
Now that lemmy.world has updated to v0.19.3, lemmy.blahaj.zone is the only major lemmy instance still on v0.18.x. I'm going to close this as there's no point in trying to support one extra instance that will hopefully update soon.
