### ISSUE TITLE
Transparent bottom bar

### ISSUE THREAD

**Issue by pvxcooper** [jwr1/interstellar#29]
Right now the app displays a solid black bar for the navigation bar on the bottom. I think it would look better changing it to be transparent like other apps. Image for reference: ![](https://files.catbox.moe/l56lla.png)

**Comment by jwr1** [comment]
I looked into adding this, and it seems it's not as simple as just setting the background color to transparent. I'll leave it open though, in case someone wants to figure it out later.

**Comment by jwr1** [comment]
I'm going to go ahead and close this. If someone wants to make a pr later, they can.
