### ISSUE TITLE
[Android] App stuck in landscape rotation after background 

### ISSUE THREAD

**Issue by SilkyPants** [jwr1/interstellar#5]
**Describe the bug**
After backgrounding the app for a while with a full screen landscaped YT video, the app is stuck in landscape mode and will not rotate into portrait until the next restart.

**To Reproduce**

1. Load a post with an embedded YouTube video 
2. Play the video in landscape/full screen 
3. Background the app
4. Wait for a long period (> 10 mins). Open other apps, or generally use device to ensure app is moved into suspension.
5. Reopen app in portrait orientation, notice the app restarts to main thread screen but locked in landscape orientation. Can freely rotate to other landscape orientation but not to portrait.

**Expected behavior**
App starts in the correct orientation, and can rotate freely to all supported orientations

**Screenshots**
![Screenshot_20240105-100554.png](https://github.com/jwr1/interstellar/assets/738172/20c31e1b-06f7-4d8d-9f7e-dd10b6527007)

**Device (please complete the following information):**

Pixel 7 running Android 14

**Comment by jwr1** [comment]
Is this still an issue after the youtube playing fix?

**Comment by SilkyPants** [comment]
@jwr1 - I managed to replicate this overnight, unfortunately. Same steps, though I had then left it overnight and when reopening the app it was stuck in Landscape mode

**Comment by jwr1** [comment]
Ok, thanks. I'll reopen it.

**Comment by jwr1** [comment]
I haven't noticed this issue at all, and we've had a lot of updates since this was opened, so I'm going to go ahead and close the issue. If anybody does notice this again, we can reopen it.
