### ISSUE TITLE
"Open link" button leads to the error page for Thread comments

### ISSUE THREAD

**Issue by FitikWasTaken** [jwr1/interstellar#52]
### Describe the bug

If you try to open reply to a thread in WebView/Browser you will get 404 not found error page

It seems like it doesn't affect microblogging view, and all comments I tested on there opened fine

### Steps to Reproduce

1. Go to Threads view
2. Open any post
3. Go to comments
4. Click "open link" -> "WebView/Browser" 
5. It opens mbin's 404 not found error page 

### Version

0.5.1

### What platform(s) are you seeing the problem on?

Android

### Additional context

It seems to lead to

https://fedia.io/m/fediverse@lemmy.world/t/971181/-/reply/6166961

While the comment URL is on

https://fedia.io/m/fediverse@lemmy.world/t/971181/-/comment/6166961

**Comment by jwr1** [comment]
Thanks for reporting! It should be good once the next update is released.

Fixed in f33254a528d676c35123f0603f20e5c1ff8733fc.
