### ISSUE TITLE
Magazine explore page extremely cramped 

### ISSUE THREAD

**Issue by breadguyyy** [jwr1/interstellar#59]
### Describe the bug

![Screenshot_20240829-224741](https://github.com/user-attachments/assets/ad45046f-75b1-4b71-b0ad-4fe8b6e92c7a)
it's a hodgepodge of numbers and cuts off community names. not particularly a bug I suppose but still

### Version

0.6.0

### What platform(s) are you seeing the problem on?

Android

**Comment by jwr1** [comment]
Fixed in 2a86fe8fc6ae959faae539db1c1b738644a02f4f
