### ISSUE TITLE
Embedded YT videos continue playing when in background or post back tapped

### ISSUE THREAD

**Issue by SilkyPants** [jwr1/interstellar#6]
**Describe the bug**
After an embedded YouTube video is playing, this will continue when the app is put into the background or if the screen is dismissed, and then continue to stack if the post is opened again

**To Reproduce**

1. Find a post with a YouTube link and open it
2. Ensure the video is playing
3. Tap back to dismiss the post screen, or background the app
4. Notice the audio for the video continues to play, regardless of the post state

**Expected behavior**
The video should stop or pause, at least on mobile, depending on the action taken. If the post is dismissed the video should be completed stopped

**Screenshots**
https://github.com/jwr1/interstellar/assets/738172/9863d534-c948-4fcd-9b18-119ebe59f017

**Device (please complete the following information):**

Pixel 7 Android 14

**Comment by jwr1** [comment]
The youtube video playing issues should be fixed in the latest release https://github.com/jwr1/interstellar/releases/tag/v0.3.0. Would you be able to verify this?

**Comment by SilkyPants** [comment]
Yep just quickly tested now and all looks fine. Both pressing back and backgrounding the app stops the playback.
