### ISSUE TITLE
Add comment/post draft system

### ISSUE THREAD

**Issue by evanfoster** [jwr1/interstellar#61]
Hey there!

### Describe the feature

Something I've noticed is that it's really easy to lose the contents of a comment/edit that hasn't been posted when on Android. I'm an oaf and I constantly provide accidental inputs. I've managed to lose several comments because I accidentally tapped on another comment/swiped a "back" gesture. I think it would be great if, on mobile platforms, a modal box popped up in those situations to confirm that you wanted to discard what you're typing before closing the text input box/leaving the comment thread.

### Additional context

Sometimes features like this can be pretty annoying. Take YouTube as an example. If I tap on someone's long comment when trying to press `see more`, I instead begin a reply to their comment with their name included as a mention. If I want to back out so I can try again to click on `see more`, I'm met with an irritating modal popup.

Interstellar's UX is better than the YouTube app, so this generally isn't a problem. However, I think it'd be cool if the modal popup only happened when the comment was substantive. My thoughts on what a non-substantive comment look like are a comment that is:
* only whitespace/newlines
* only a username mention
* only a magazine/community mention
* only punctuation
* only one word

I don't know if some of these would be a good idea or not since they might break the principle of least astonishment, but I figured I'd throw it out there 

Thanks again for all you do!

**Comment by jwr1** [comment]
Yeah, I could see that being helpful.

Would you rather this, or maybe a drafting system instead where it saves your post or reply if you haven't submitted it yet. That way, it wouldn't pop up an annoying modal when you try to exit, and it saves it in case you want to come back to it later. Just a thought.

**Comment by evanfoster** [comment]
Ah, a drafting system is an even better idea. If I recall correctly, that's what Relay for Reddit used to do and I loved that.

**Comment by jwr1** [comment]
Complete in 5be0dedf5607678fa34911e047bbc913cdc7187e.
