### ISSUE TITLE
Links aren't rendered correctly

### ISSUE THREAD

**Issue by FitikWasTaken** [jwr1/interstellar#76]
### Describe the bug

Links in microblog posts are rendered as \<https://example.com/ > And aren't clickable

![Screenshot_20241214-053103](https://github.com/user-attachments/assets/daafb13d-6718-46c6-819e-b5efe2501a7b)

### Version

0.7.0

### What platform(s) are you seeing the problem on?

Android

### Additional context

It wasn't a case with the previous version, so some change broke them

**Comment by jwr1** [comment]
Thanks for the issue. Just a very simple change was needed. I'll release it as soon as I fix your other issues.

Fixed in 657a1c5d9ca34e617083881258384670f6b080eb.
