### ISSUE TITLE
Long microblogs get cut off

### ISSUE THREAD

**Issue by FitikWasTaken** [jwr1/interstellar#78]
### Describe the bug

If the original microblog exceed certain amount of characters it gets cut off in the interstellar app, even when clicked on it

This is the same microblog on the web:
![Screenshot_20241214-152945](https://github.com/user-attachments/assets/10b63224-01ff-4143-bf25-3f80564a8fa6)

And this is in the app: 
![Screenshot_20241214-152932](https://github.com/user-attachments/assets/61cd2417-d4cc-4005-9ccf-d824d4b6fc03)

### Steps to Reproduce

1. Go to the Microblogging view
2. Find a long microblog on there
3. Click on it and see that it is cut off

### Version

0.7.0

### What platform(s) are you seeing the problem on?

Android

### Additional context

It wasn't a case before the last update

**Comment by jwr1** [comment]
It also fixed this issue as well.

Fixed in 657a1c5d9ca34e617083881258384670f6b080eb.
